export const BLOGS = [
    {
        title: "Transforming Business with AI Integration",
        desc: "Discover how AKRE's AI solutions are helping businesses automate processes and gain competitive advantages through intelligent automation.",
        image: "/images/blog1.svg",
        category: "AI Solutions",
        author: "Dr. Anil Sharma",
        authorRole: "Head of AI Research",
        authorCompany: "AKRE",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
    },
    {
        title: "Cloud-Native Development: The AKRE Way",
        desc: "Learn about our approach to building scalable, resilient cloud applications on AWS, Azure, and Google Cloud platforms.",
        image: "/images/blog2.svg",
        category: "Cloud Services",
        author: "Priya Nair",
        authorRole: "Cloud Solutions Architect",
        authorCompany: "AKRE",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person2.jpg",
    },
    {
        title: "The Future of Enterprise Software Development",
        desc: "How AKRE is helping enterprises modernize their legacy systems with cutting-edge technology stacks and microservices architecture.",
        image: "/images/blog3.svg",
        category: "Enterprise Solutions",
        author: "Rajesh Verma",
        authorRole: "CTO",
        authorCompany: "AKRE",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person3.jpg",
    },
    {
        title: "Workflow Automation: Case Studies",
        desc: "Real-world examples of how AKRE's workflow automation solutions have transformed business operations for our clients.",
        image: "/images/blog1.svg",
        category: "Automation",
        author: "Neha Kapoor",
        authorRole: "Automation Lead",
        authorCompany: "AKRE",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person4.jpg",
    },
    {
        title: "Building Secure Digital Experiences",
        desc: "AKRE's comprehensive approach to cybersecurity in application development and deployment.",
        image: "/images/blog2.svg",
        category: "Security",
        author: "Vikram Singh",
        authorRole: "Security Expert",
        authorCompany: "AKRE",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
    },
    {
        title: "The Rise of Full-Stack Development",
        desc: "How AKRE's full-stack development expertise delivers end-to-end solutions for complex business challenges.",
        image: "/images/blog3.svg",
        category: "Development",
        author: "Anjali Mehta",
        authorRole: "Lead Developer",
        authorCompany: "AKRE",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person2.jpg",
    },
];
